{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-firewalla.fullname" . }}
  labels:
    {{- include "external-dns-firewalla.labels" . | nindent 4 }}
type: Opaque
stringData:
  HMAC_SECRET: {{ required "secret.hmacSecret is required when secret.create=true" .Values.secret.hmacSecret | quote }}
{{- end }}
