apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-dns-firewalla.fullname" . }}
  labels:
    {{- include "external-dns-firewalla.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "external-dns-firewalla.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: webhook
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
